# Generated by Django 6.0.1 on 2026-01-28 17:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('certificate', 'Certificate'), ('job_history', 'Job History'), ('skill', 'Skill'), ('milestone', 'Milestone'), ('community', 'Community Contribution')], max_length=20)),
                ('internal_id', models.CharField(max_length=100, unique=True)),
                ('validation_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onchain_data', models.JSONField()),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proof_type', 'created_at'], name='documents_d_proof_t_18cc79_idx'), models.Index(fields=['user_id', 'proof_type'], name='documents_d_user_id_52a6f9_idx'), models.Index(fields=['internal_id'], name='documents_d_interna_be82e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('Talk', 'Talk'), ('Article', 'Article'), ('Open Source', 'Open Source'), ('Community Role', 'Community Role')], max_length=20)),
                ('platform_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=7)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_contribution', to='documents.document')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(max_length=255)),
                ('issuer_name', models.CharField(max_length=255)),
                ('completion_date', models.CharField(max_length=7)),
                ('credential_type', models.CharField(choices=[('Course', 'Course'), ('Bootcamp', 'Bootcamp'), ('Workshop', 'Workshop'), ('Award', 'Award')], max_length=20)),
                ('program_category', models.CharField(max_length=100)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='documents.document')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'txt', 'doc', 'docx'])])),
                ('file_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='documents.document')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('employer_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('intern', 'Intern'), ('contributor', 'Contributor'), ('contract', 'Contract')], max_length=20)),
                ('start_date', models.CharField(max_length=7)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
                ('job_category', models.CharField(max_length=100)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Job histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('Promotion', 'Promotion'), ('Award', 'Award'), ('Recognition', 'Recognition'), ('Key Result', 'Key Result')], max_length=20)),
                ('issuer_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=7)),
                ('milestone_summary', models.TextField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='documents.document')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='documents.document')),
            ],
            options={
                'ordering': ['skill_category', 'skill_name'],
            },
        ),
    ]
